"""
This type stub file was generated by pyright.
"""

from typing import Any

import _cffi_backend

ffi = ...

def play(data, samplerate=None, mapping=None, blocking=False, loop=False,
         **kwargs: Any) -> Any: ...

def wait(ignore_errors=True) -> Any:
    ...
